# Generated by Django 5.0.3 on 2024-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heppy_pet_app', '0002_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
